name: Prepare Release for DebugPrint Plugin

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  prepare_release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code (latest version of the action)
    - name: Checkout repository
      uses: actions/checkout@v4

    # Remove all files except .uplugin, Source, and Resource directories
    - name: Clean up unnecessary files
      run: |
        find . -mindepth 1 -not -name '*.uplugin' -not -path './Source*' -not -path './Resource*' -exec rm -rf {} +

    # Create a ZIP archive of the plugin with the required files
    - name: Zip Plugin
      run: zip -r DebugPrint-v${{ github.event.release.tag_name }}.zip .

    # Upload the ZIP archive as a release asset using a more up-to-date action
    - name: Upload Plugin to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: DebugPrint-v${{ github.event.release.tag_name }}.zip
        asset_name: DebugPrint-v${{ github.event.release.tag_name }}.zip
        tag: ${{ github.event.release.tag_name }}