name: Prepare Release for DebugPrint Plugin

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  prepare_release:
    runs-on: ubuntu-latest

    steps:
    # Step to check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step to remove all files except .uplugin, Source, and Resource directories
    - name: Clean up unnecessary files
      run: |
        find . -mindepth 1 -not -name '*.uplugin' -not -path './Source*' -not -path './Resource*' -exec rm -rf {} +

    # Step to create a ZIP archive of the plugin with the required files
    - name: Zip Plugin
      run: zip -r DebugPrint-v${{ github.event.release.tag_name }}.zip .

    # Step to upload the ZIP archive as a release asset
    - name: Upload Plugin to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: DebugPrint-v${{ github.event.release.tag_name }}.zip
        asset_name: DebugPrint-v${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
